name: zepair
description: "Zepair: the mobile app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version number
version: 1.0.0+1

environment:
  sdk: ^3.5.4


# here will be all the dependencies or pakages that project will use
dependencies:
  flutter:
    sdk: flutter
    


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  lottie: ^3.2.0
  pinput: ^3.0.1
  disclosure: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

# here will go all the asset's path we will use in project
  assets:
    - assets/images/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
  #         style: italic
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

    - family: Baloo-Bhai-2
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
        - asset: assets/fonts/BalooBhai2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooBhai2-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
