name: zepair
description: "Zepair: the mobile app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version number
version: 1.0.0+1

environment:
  sdk: ^3.5.4


# here will be all the dependencies or pakages that project will use
dependencies:
  flutter:
    sdk: flutter
    
  # Pakages
  cupertino_icons: ^1.0.8
  gap: ^3.0.1

  disclosure: ^2.2.0
  lottie: ^3.2.0 # lottie animations
  pinput: ^3.0.1 # otp input field
  url_launcher: ^6.3.1
  convex_bottom_bar: ^3.2.0
  firebase_core: ^3.12.0

  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  geolocator: ^13.0.2
  razorpay_flutter: ^1.4.0
  http: ^1.3.0

  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  velocity_x: ^4.3.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

# here will go all the asset's path we will use in project
  assets:
    - assets/images/
    - assets/lotties/
    - assets/images/Devices_Icons/
  #   - images/a_dot_ham.jpeg


  # Custom Fonts paths here
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf

    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

    - family: Baloo-Bhai-2
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
        - asset: assets/fonts/BalooBhai2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooBhai2-Bold.ttf
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
